### PR TITLE
Some minor updates

### PR DESCRIPTION
**Pull request by Noogear**
* Compatible with KeepInventory and Soul Bound
* Custom inventory title
* Fix the inaccuracy of remove-corpse-after-interaction-minutes
* Keep corpses above the void

### CODE REVIEW

**Comment by connormck333** [comment]
Hey, thanks for this. LGTM. Please just answer my one question and I can merge.

**Comment by Noogear** [comment]
> Hey, thanks for this. LGTM. Please just answer my one question and I can merge.

Hello. What's the problem?

**Comment by connormck333** [comment]
What is the purpose of the change in CorpseListener? I am unsure of what it is actually doing

**Comment by Noogear** [comment]
> What is the purpose of the change in CorpseListener? I am unsure of what it is actually doing

There're some binding plugins that can stop items from getting lost. The bound items ain't gonna be added to the drops list. So loop through this list. If an item in the player's inv ain't in this list, it means the item's already bound to this player.

**Comment by connormck333** [comment]
Amazing, thanks for the contribution. Have you a spigot account and I can add you as a contributor?

**Comment by Noogear** [comment]
> Amazing, thanks for the contribution. Have you a spigot account and I can add you as a contributor?

Yeah, I'm MADAQ. I'm the one in the comments. LOL. Happy New Year!

**Comment by connormck333** [comment]
Great :) Happy New Year!

**Pull request merged**
